[theme]
base = "light"
primaryColor = "#007AFF"
backgroundColor = "#F5F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D1D1F"
font = "sans serif"
GRAPHHOPPER_API_KEY = "ff9ba191-28ed-4d04-b171-0f607e4020ad"
